//
//  MockData.swift
//  RecipeApp
//
//  Created by Muhammed Tanriverdi on 11/02/2021.
//  Copyright © 2021 S3soft. All rights reserved.
//

// MARK: - MOCK DATA

let sampleRecipes: [Recipe] = [
    Recipe(
      title: "Baked Shrimp Scampi",
      comments: "Modified by reducing butter and salt.  Substituted frozen shrimp instead of fresh 12-15 count (butterflied, tails on).",
      calories: 2565,
      fat: 159,
      satfat: 67,
      carbs: 76,
      fiber: 4,
      sugar: 6,
      protein: 200,
      image: "food-1",
      rating: 5,
      serves: 4,
      preparation: 20,
      cooking: 0,
      instructions: [
        "Preheat the oven to 425 degrees F.",
        "Defrost shrimp by putting in cold water, drain. Place the shrimp in serving dish (9x13 or 2 quart casserole) and toss gently with the olive oil, wine, 1 teaspoons salt, and 1 teaspoon pepper. Allow to sit at room temperature while you make the butter and garlic mixture.",
        "In a small bowl, mash the softened butter with the garlic, shallots, parsley, rosemary, red pepper flakes, lemon zest, lemon juice, egg yolk, panko, 1/2 teaspoon salt, and 1/4 teaspoon of pepper until combined.",
        "Spread the butter mixture evenly over the shrimp. Bake for 10 to 12 minutes until hot and bubbly. If you like the top browned, place under a broiler for 1-3 minutes (keep an eye on it). Serve with lemon wedges and French bread.",
        "Note: if using fresh shrimp, arrange for presentation. Starting from the outer edge of a 14-inch oval gratin dish, arrange the shrimp in a single layer cut side down with the tails curling up and towards the center of the dish. Pour the remaining marinade over the shrimp. ",
      ],
      ingredients: [
        "2/3 cup panko",
        "1/4 teaspoon red pepper flakes",
        "1/2 lemon, zested and juiced",
        "1 extra-large egg yolk",
        "1 teaspoon rosemary, minced",
        "3 tablespoon parsley, minced",
        "4 clove garlic, minced",
        "1/4 cup shallots, minced",
        "8 tablespoon unsalted butter, at room temperature",
        "2 tablespoon dry white wine",
        "Freshly ground black pepper",
        "Kosher salt",
        "3 tablespoon olive oil",
        "2 pound frozen shrimp"
      ],
      isEditorChoice: true,
      isTrending: false
    ),
    Recipe(
      title: "Strawberries Romanov (La Madeleine copycat)",
      comments: "",
      calories: 123,
      fat: 22,
      satfat: 12,
      carbs: 0,
      fiber: 34,
      sugar: 12,
      protein: 2,
      image: "food-2",
      rating: 3,
      serves: 4,
      preparation: 30,
      cooking: 110,
      instructions: [
        "Wash strawberries and cut the tops off.",
        "Let strawberries drain.",
        "Mix together heavy whipping cream, powdered sugar, and the brandy.",
        "Beat with a mixer till this becomes thick.",
        "Place strawberries into glasses and spoon over the sauce."
      ],
      ingredients: [
        "2 tbsp powdered sugar",
        "1/2 pt heavy whipping cream",
        "1 lb strawberries, (2 pints)",
        "4 tbsp brandy"
      ],
      isEditorChoice: true,
      isTrending: true
    ),
    Recipe(
      title: "Tomato Basil Soup (La Madeleine copycat)",
      comments: "",
      calories: 231,
      fat: 23,
      satfat: 45,
      carbs: 12,
      fiber: 23,
      sugar: 1,
      protein: 32,
      image: "food-3",
      rating: 4,
      serves: 2,
      preparation: 25,
      cooking: 15,
      instructions: [
        "Combine tomatoes, juice/and or possibly stock in saucepan.",
        "Simmer 30 min. Puree, along with the basil leaves, in small batches, in blender or food processor or use an immersion blender in the pan.",
        "Return to saucepan and add in cream and butter, while stirring over low heat.",
        "Garnish with basil leaves and serve with your favorite bread.",
      ],
      ingredients: [
        "4 c tomatoes, minced, peeled, and cored",
        "4 cup vegetable stock",
        "12 basil leaves",
        "1 c heavy cream",
        "1/4 lb unsalted butter",
        "Salt",
        "1/4 tsp black pepper"
      ],
      isEditorChoice: false,
      isTrending: false
    ),
    Recipe(
      title: "John Thorne's Pecan Pie",
      comments: "Does not use corn syrup",
      calories: 542,
      fat: 123,
      satfat: 56,
      carbs: 212,
      fiber: 9,
      sugar: 59,
      protein: 83,
      image: "food-4",
      rating: 5,
      serves: 6,
      preparation: 30,
      cooking: 5,
      instructions: [
        "Preheat oven to 350F. In a large saucepan, heat the brown sugar, golden syrup and butter to the boiling point.",
        "Stirring constantly and scraping back any foam that clings to the side of the pan, let this mixture boil for about 1 minute.",
        "Remove from the heat and let cool while, in a separate bowl, you beat the eggs until creamy.",
        "When the boiled syrup has cooled, beat in the eggs, salt and pecans. Pour into the unbaked pie shell and bake for about 50 minutes.",
        "Notes: A little cream (about 1/4 to 1/2 cup) mixed into a pecan pie filling before baking gives it a richer, lighter texture.",
        "For a sweeter, lighter pie: add more sugar and use fewer pecans; for a denser, less sweet pie: add more pecans and use less sugar.",
        "The buttery flavour and the lard-induced flakiness of a butter and lard crust make it the perfect one for a perfect pecan pie.",
        "And a Southern pecan pie authority I know suggests that you roll out the dough a little thicker than usual; a thick, richly shortened crust provides an appetizing balance to the sweetness of the filling. ",
      ],
      ingredients: [
        "1/4 tsp salt ",
        "3 eggs ",
        "4 tbsp butter ",
        "2 tbsp dark rum ",
        "2/3 cup golden syrup ",
        "1 cup dark brown sugar, well-packed",
        "2 cup pecans, chopped ",
        "9-inch unbaked pie shell"
      ],
      isEditorChoice: true,
      isTrending: false
    ),
    Recipe(
      title: "Smoked Salmon Ebelskivers",
      comments: "If dill is not available, add 1 tsp of Old Bay seasoning to the batter in place of the salt and pepper.",
      calories: 1200,
      fat: 300,
      satfat: 23,
      carbs: 5,
      fiber: 90,
      sugar: 150,
      protein: 200,
      image: "food-5",
      rating: 5,
      serves: 4,
      preparation: 30,
      cooking: 60,
      instructions: [
        "Preheat oven to 200F.",
        "In a large bowl, whisk together the flour, sugar, baking powder, salt, and pepper.",
        "In a small bowl, lightly whisk the egg yolks, then whisk in the milk, 2 tablespoons of melted butter and lemon juice.",
        "Add the yolk mixture to the flour mixture and, using a wooden spoon, stir until well blended. The batter will be lumpy.",
        "In a clean bowl, using an electric mixer on high speed, beat the egg whites until stiff, but not dry, peaks form.",
        "Using a silicone spatula, fold about one-third of the egg whites into the batter to lighten it, then fold in the rest just until no white streaks remain. Stir in fresh dill.",
        "Brush the wells of the ebelskiver pan with some of the remaining melted butter and place over medium heat. When the butter starts to bubble, add about 1 tablespoon batter to each well.",
        "Working quickly, carefully spoon about 1/2 teaspoon of the smoked salmon into the center of each pancake, then spoon about 1/2 teaspoon of the cream cheese on top. Top each with another 1 tablespoon batter. (Alternatively, gently mix the cream cheese and salmon together. Spoon about 1 teaspoon into the center of each pancake)",
        "Cook until the bottoms of the pancakes are lightly browned and crisp, 3-5 minutes. Use 2 short wooden skewers to turn all the  pancakes and cook until lightly browned on the second side, about 3 minutes longer.",
        "Transfer the finished pancakes to a platter and keep warm  in the oven while you repeat to make 2 more batches. Serve right away.",
      ],
      ingredients: [
        "1 cup all-purpose flour",
        "1 1/2 tsp sugar",
        "1/2 tsp baking powder",
        "1/4 tsp salt",
        "1/2 tsp pepper, freshly ground",
        "2 large eggs, separated",
        "1 cup milk",
        "3 tbsp unsalted butter, melted and slightly cooled, divided use",
        "1 tsp fresh lemon juice",
        "1/4 cup fresh dill, chopped and firmly packed",
        "3 1/2 tbsp smoked salmon, minced (about 4 oz)",
        "3 1/2 tbsp whipped-style cream cheese, at room temperature",
      ],
      isEditorChoice: false,
      isTrending: true
    ),
    Recipe(
      title: "Godiva Angel Pie",
      comments: "",
      calories: 232,
      fat: 1,
      satfat: 0,
      carbs: 0,
      fiber: 95,
      sugar: 3,
      protein: 78,
      image: "food-6",
      rating: 5,
      serves: 6,
      preparation: 60,
      cooking: 75,
      instructions: [
        "TO MAKE SHELL: Preheat oven to 300 degrees. In mixer bowl, beat egg whites until foamy.",
        "Beat in salt and cream of tartar and beat until soft peaks form. Add sugar, a tablespoon at a time, beating after each addition.",
        "Continue until very stiff peaks form. Fold in nuts and vanilla. Lightly butter a metal 8-inch pie plate. (Do NOT use glass.)",
        "Spoon meringue into pan lightly, building up the edges to come at least 1/2 inch above the side of the pan.",
        "Bake in preheated 300 degree oven for 35 to 40 minutes until light brown. Cool completely before adding filling.",
        "TO MAKE FILLING: Melt chocolate and water in a pan over hot, but not boiling, water, stirring occasionally, to blend.",
        "Add vanilla and chocolate mixture (cooled) to whipped cream and pile into meringue shell, swirling top with spatula.",
        "Be sure to cool the chocolate mixture before adding to the whipped cream. If it is too warm, the mixture will thin out.If this happens, chill until it is thick enough to put in shell.",
      ],
      ingredients: [
        "4 (1 oz.) squares Godiva cooking chocolate or 4 oz. Baker's German sweet chocolate",
        "1/2 tsp vanilla",
        "1 cup pecans, finely chopped",
        "1/2 cup sugar",
        "1/8 tsp cream of tartar",
        "1/8 tsp salt",
        "2 egg whites, at room temperature",
        "3 tbsp water",
        "1 tsp vanilla",
        "1 cup heavy cream, whipped"
      ],
      isEditorChoice: true,
      isTrending: true
    ),
    Recipe(
      title: "Spaetzle",
      comments: "Dough recipe from Emeril, sauce recipe from Guy Fieri",
      calories: 56,
      fat: 3,
      satfat: 2,
      carbs: 0,
      fiber: 0,
      sugar: 5,
      protein: 0,
      image: "food-7",
      rating: 2,
      serves: 2,
      preparation: 20,
      cooking: 0,
      instructions: [
        "Bring a saucepan of salted water it a boil, reduce the heat, and maintain a simmer.",
        "In a bowl, stir all the ingredients together (eggs, flour, milk, salt, baking powder, and nutmeg).",
        "Place a colander over the pan, pour about1/4 of the batter into the colander, and press through the holes with a plastic spatula into the hot water.",
        "When the spatzle starts to float to the surface, cover the pan and keep covered until the spatzle appears to swell and is fluffy.",
        "Remove the dumplings and repeat the procedure with the remaining batter.",
        "In a medium saute pan, add butter, and melt over medium heat until butter turns a light brown. Add garlic and cook until it becomes lightly colored.",
        "Add spaetzle to the pan to heat through. Add parsley, cheese, salt and pepper, to taste.",
      ],
      ingredients: [
        "2 teaspoon fresh parsley, chopped",
        "1 teaspoon garlic, minced",
        "3 tablespoon butter",
        "1 pinch nutmeg",
        "1/4 teaspoon baking powder",
        "1 teaspoon salt",
        "1/2 cup milk",
        "1 1/2 cup flour, sifted",
        "2 eggs, slightly beaten",
        "2 tablespoon finely grated Parmesan, plus extra for garnish",
        "Salt and freshly ground black pepper"
      ],
      isEditorChoice: true,
      isTrending: false
    ),
    Recipe(
      title: "Pot Roast Carbonnade",
      comments: "I like to serve this over mashed potatoes.",
      calories: 400,
      fat: 20,
      satfat: 20,
      carbs: 40,
      fiber: 10,
      sugar: 0,
      protein: 150,
      image: "food-8",
      rating: 5,
      serves: 6,
      preparation: 20,
      cooking: 30,
      instructions: [
        "Preheat the oven to 325 degrees F.",
        "In a large Dutch oven over medium-low heat, add the bacon and cook until it renders its fat and almost becomes crispy.",
        "Remove it with a slotted spoon to a plate.",
        "Add the onions, season with salt and pepper, to taste, and cook over low heat until they are deep in color and caramelized, about 30 minutes.",
        "Remove the onions to a plate, leaving as much fat in the pot as possible.",
        "Add the vegetable oil and mix it with the bacon fat. Raise the heat to high.",
        "Season the beef liberally with salt and pepper and sear, in batches, until nicely browned on both sides.",
        "Once the meat is browned, add the first batch of meat back to the pan along with the onions, carrots and bacon.",
        "Sprinkle in the flour and stir. Cook for 1 minute before deglazing the pan with the beer.",
        "Add the remaining ingredients and bring the mixture to a simmer.",
        "Cover the pot and put it in the oven to braise until the beef is tender, about 2 hours.",
        "Remove the pot from the oven and transfer the pot roast to a serving dish.",
      ],
      ingredients: [
        "1/2 pound bacon, cut into large lardons",
        "2 medium onions, sliced",
        "Kosher salt and freshly ground black pepper",
        "1 tablespoon vegetable oil",
        "1 1/2 pound beef chuck, cut into large cubes",
        "5 carrots, peeled and cut into large chunks",
        "1 tablespoon all-purpose flour",
        "12 ounce beer (dark or light)",
        "6 prunes",
        "1 tablespoon dried thyme",
        "1 cup beef stock"
      ],
      isEditorChoice: false,
      isTrending: true
    )
]


